### PR TITLE
add footer

### LINKED ISSUE #50: Create Footer Bar
## Summary

Create the Footer bar based upon the agreed upon layout found [here](https://www.figma.com/file/Pqh5K3G3VcjhDImekaMeWl/UDD-mockup?node-id=2%3A1872). Please note, do not worry about styling the Nav bar to match the exact colors and buttons we have, rather make sure the layout matches

## Acceptance Criteria

- Create a branch called "footer_bar"
- Use Ant Design for the buttons
- In parts folder
- Code is well commented
- Code functions as intended with no bugs

### PR DESCRIPTION
**Pull request by robertjallen**
# Description

Fixes # (issue # from issue tracker)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?
- [ ] Unit Tests
- [ ] Integration Tests
- [ ] User Tests

# Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by robertjallen** [comment]
[](url)
Screenshot 2020-12-23 093133

**Review by JessBonanno — CHANGES_REQUESTED** [review]
I pulled the branch locally.  Nice work, you're off to a good start.  I have some change requests:
- There are a few warnings that need to be addressed in the console regarding the "blank" targets on the a tags.
- There is an error regarding "class" attribute rather than "className" on the a tags as well.
- The footer is considered a "part" of a page rather than a "component",  would you refactor to the part folder please.  "Components" would be for smaller items such as buttons etc.
- I noticed you added footer css to the app.css file, would you refactor to a footer.css file please?
- Just a heads up about the branch naming conventions.  A branch name was requested in the ticket.  I was unable to find it when doing a git fetch because I was looking for the name on the ticket.
Thanks Rob!

**Comment by JessBonanno** [comment]
I also just noticed there is a bit of commented out code in the app.css file.  Specifically line 82 is throwing an error for me because of the extra characters in the comment.

**Comment by robertjallen** [comment]
I think I got everything including the commented out code in App.js

**Comment by robertjallen** [comment]
> I pulled the branch locally. Nice work, you're off to a good start. I have some change requests:
> 
> * There are a few warnings that need to be addressed in the console regarding the "blank" targets on the a tags.
> * There is an error regarding "class" attribute rather than "className" on the a tags as well.
> * The footer is considered a "part" of a page rather than a "component",  would you refactor to the part folder please.  "Components" would be for smaller items such as buttons etc.
> * I noticed you added footer css to the app.css file, would you refactor to a footer.css file please?
> * Just a heads up about the branch naming conventions.  A branch name was requested in the ticket.  I was unable to find it when doing a git fetch because I was looking for the name on the ticket.
>   Thanks Rob!

I think I got everything you mentioned including the commented out code in APP.js

Let me know if you spot anything else

**Review by JessBonanno — APPROVED** [review]
Thanks for addressing my suggestions.  This looks great.
- I added .eslintcache to the .gitignore and pushed that change to this PR so we will have to manually remove the .eslintcache that is already in main after this is merged.

**Pull request merged**
