### PR TITLE
add edit nav-bar and signup

### PR DESCRIPTION
**Pull request by robertjallen**
# Description
Fixes # (issue # from issue tracker)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ X] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?
- [ ] Unit Tests
- [ ] Integration Tests
- [ ] User Tests

# Checklist
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X ] There are no merge conflicts

### CODE REVIEW

**Review by CalJersey — COMMENTED** [review]
Hi Rob, Nice work. I feel like I missed something. Where did all this come from?

**Comment by robertjallen** [comment]
Someone needs to merge this please. I really don't want to get in the habit of merging my own pull requests. Its ready to Merge.

**Comment by CalJersey** [comment]
Happy to merge it, but what is the origin of the project? Did I miss a call or discussion on Slack officially launching development on the site?

**Pull request merged**
